class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end


  def create
    # we call Post.new to create a new instance of Post.
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      # if saving the instance of post to the database was successful, we display a success message using flash[:notice]
      flash[:notice] = 'Post was saved.'
      # and redirect the user to the route generated by @post.
      # Redirecting to @post will direct the user to the posts show view.
      redirect_to @post
    else
      # if saving the instance of post was not successful, we display an error message and render the new view again.
      flash[:error] = 'There was an error saving the post. Please try again'
      render :new
    end
  end


  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post successfully updated!"
      redirect_to @post
    else
      flash[:error] = "Error updating post, please try again"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to posts_path
    else
      flash[:error] = "Post could not be deleted, please try again"
    end

  end

end
